### PR TITLE
Escape quotes in shell code stored in gitconfig.

### PR DESCRIPTION
**Pull request by rose00**
https://bugs.openjdk.java.net/browse/SKARA-99

Progress
--------
- [x] Change must not contain extraneous whitespace
- [x] Change must be properly reviewed

Approvers
---------
 * Erik Helin ([ehelin](@edvbld) - **Reviewer**)

### CODE REVIEW

**Comment by rose00** [comment]
/integrate

(Hey, where are the `/foo` commands documented?)

**Comment by edvbld** [comment]
@rose00 we haven't really had time to write up all the documentation yet, that is coming on the Skara wiki. As for a "review" command, maybe, but all platforms feature review functionality (plus the Skara CLI tooling also supports `git pr approve`). On GitHub the actually not so invisible button appears when you click the "Files changed" tab :smile_cat:

**Comment by rose00** [comment]
Thanks for the tour!

**Pull request closed without merging**
