### PR TITLE
2411: Host::user should throw when failing

### PR DESCRIPTION
**Pull request by erikj79**
The implementations of Host::user are all currently returning Optional::empty on any error return code. This means a that a bot checking for the existence of a user encounters an error with a host, e.g. JBS, it will think the user doesn't exist and take actions based on that assumption. This would be correct if the server response was 404, but in all other cases, it would be better if the WorkItem failed to be automatically retried later.

This patch changes the onError lambda for these methods so that it only handles the 404 case, and in all other cases lets the RestException be thrown. This matches the behavior of most other methods in these classes.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace

### Issue
 * [SKARA-2411](https://bugs.openjdk.org/browse/SKARA-2411): Host::user should throw when failing (**Bug** - P2)

### Reviewers
 * [Kevin Rushforth](https://openjdk.org/census#kcr) (@kevinrushforth - **Reviewer**)
 * [Zhao Song](https://openjdk.org/census#zsong) (@zhaosongzs - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/skara.git pull/1698/head:pull/1698` \
`$ git checkout pull/1698`

Update a local copy of the PR: \
`$ git checkout pull/1698` \
`$ git pull https://git.openjdk.org/skara.git pull/1698/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1698`

View PR using the GUI difftool: \
`$ git pr show -t 1698`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/skara/pull/1698.diff">https://git.openjdk.org/skara/pull/1698.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/skara/pull/1698#issuecomment-2488858043)
</details>

### CODE REVIEW

**Review by kevinrushforth — APPROVED** [review]
This looks good. to me.

One question about the Description:

> The implementations of Host::user are all currently returning Optional::empty on any error return code

I think you mean they are all currently returning `Optional.of(JSON.of())` right? And that after this change you will continue to return that for 404, and return `Optional.empty()` (which will throw) for all other cases.

**Comment by erikj79** [comment]
> One question about the Description:
> 
> > The implementations of Host::user are all currently returning Optional::empty on any error return code
> 
> I think you mean they are all currently returning `Optional.of(JSON.of())` right? And that after this change you will continue to return that for 404, and return `Optional.empty()` (which will throw) for all other cases.

No, the description is about the `Host::user` method, which in turn uses `RestRequest`, providing a lambda for `onError`. What you are describing is what that lambda does, which the Host::user methods will translate to `Optional<HostUser>` that either contains an instance of HostUser, or is empty.

**Comment by kevinrushforth** [comment]
Thanks for the clarification.

**Review by zhaosongzs — APPROVED** [review]

**Comment by erikj79** [comment]
Thanks!

/integrate

**Pull request closed without merging**
