### PR TITLE
1516: Command 'git pr integrate' gets error message 'time out'

### PR DESCRIPTION
**Pull request by lgxbslgx**
Hi all,

I tried the command `git pr integrate 1341` to integrate SKARA-1495. The command replies `error: timed out waiting for response to /integrate command`. It is because the bot added a comment `@lgxbslgx Pushed as commit XXX.` so that this line is not started with `Pushed as commit`.

This patch fixes the bug by using a pattern matcher instead of judging the beginning of the line. And I verified this patch by using the command `git pr integrate 1344` to integrate SKARA-1463 just now. It works well and replies `@lgxbslgx Pushed as commit 35b23b882393c33565e49ec0399adba7e8eb2f5b`. But I have not verified the sponsor flow because I don't have a chance to do that now.

Thanks for taking the time to review.

Best Regards,
-- Guoxion

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace

### Issue
 * [SKARA-1516](https://bugs.openjdk.org/browse/SKARA-1516): Command 'git pr integrate' gets error message 'time out'

### Reviewers
 * [Erik Joelsson](https://openjdk.org/census#erikj) (@erikj79 - **Reviewer**)
 * [Magnus Ihse Bursie](https://openjdk.org/census#ihse) (@magicus - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/skara pull/1352/head:pull/1352` \
`$ git checkout pull/1352`

Update a local copy of the PR: \
`$ git checkout pull/1352` \
`$ git pull https://git.openjdk.org/skara pull/1352/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1352`

View PR using the GUI difftool: \
`$ git pr show -t 1352`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/skara/pull/1352.diff">https://git.openjdk.org/skara/pull/1352.diff</a>

</details>

### CODE REVIEW

**Comment by magicus** [comment]
Is there no tests for this? Can you please add one, if not, or update it, if it does not test this properly.

**Comment by lgxbslgx** [comment]
All the code in cli module don’t have tests now. It seems be hard to add tests to verify the client commands so the previous developers didn’t add any test for it. I don’t really know whether it has a good way to add such test, but I am still thinking.

**Review by erikj79 — APPROVED** [review]

**Comment by magicus** [comment]
Ah, right, it's the CLI. *duh* 

I do think we should have tests for them, but setting up testing scaffolding for CLI testing is way beyond this PR. But if you feel like doing it, please go ahead! Especially a popular command like "git skara sync" would benefit from having automated testing.

**Review by magicus — APPROVED** [review]

**Comment by lgxbslgx** [comment]
Thanks for the reviews. Integrating.

/integrate

**Pull request closed without merging**
