### PR TITLE
1682: PullRequestBot::getPeriodicItems takes too long

### PR DESCRIPTION
**Pull request by erikj79**
Similar to the NotifyBot in [SKARA-1680](https://bugs.openjdk.org/browse/SKARA-1680), the PullRequestBot is also suffering from spending a very long time in the very first round of getPeriodicItems after a bot restart. The last time we redeployed this bot, it took ~40 minutes. This was long enough to trigger several users to ask if Skara was having issues.

The cause is similar. There is an `isReady` call for each PR, which checks for comments. The comment checking here is even worse than for the NotifyBot because every PR is checked for comments, not just those that match the "rfr" or "integrated" labels.

My proposed solution is similar. We need to move this expensive evaluation to the relevant WorkItems where they can run concurrently instead of serially in `getPeriodicItems`. I chose to make the call from the abstract superclass `PullRequestWorkItem`. This does add the check unnecessarily to the `LabelerWorkItem`, but that one is running so rarely that I don't think it matters performance wise. For correctness, I don't think it hurts checking an extra time.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace

### Issue
 * [SKARA-1682](https://bugs.openjdk.org/browse/SKARA-1682): PullRequestBot::getPeriodicItems takes too long

### Reviewers
 * [Zhao Song](https://openjdk.org/census#zsong) (@zhaosongzs - Committer) ⚠️ Review applies to [1ead6076](https://git.openjdk.org/skara/pull/1423/files/1ead6076eb1f747904b759cecc9b28ec813432ec)
 * [Magnus Ihse Bursie](https://openjdk.org/census#ihse) (@magicus - **Reviewer**) ⚠️ Review applies to [43272b56](https://git.openjdk.org/skara/pull/1423/files/43272b5692f728a9b59a5089be79c799e684c661)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/skara pull/1423/head:pull/1423` \
`$ git checkout pull/1423`

Update a local copy of the PR: \
`$ git checkout pull/1423` \
`$ git pull https://git.openjdk.org/skara pull/1423/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1423`

View PR using the GUI difftool: \
`$ git pr show -t 1423`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/skara/pull/1423.diff">https://git.openjdk.org/skara/pull/1423.diff</a>

</details>

### CODE REVIEW

**Review by zhaosongzs — APPROVED** [review]
LGTM, just a small question, what don't we move `isReady()` to `PullRequestWorkItem`?

**Comment by erikj79** [comment]
> LGTM, just a small question, why don't we move `isReady()` to `PullRequestWorkItem`?

In this patch, it was laziness mostly. Moving it would require providing the underlying data to the WorkItem as well, either by calling the bot for it or adding as additional fields in the work item.

I did think some more on this patch since yesterday, and realized that we will be doing the isReady check quite a lot more with this change. This is because CheckWorkItem and PullRequestCommandWorkItem often spawn each other in sequence, and now each of those instances would repeat the check unnecessarily (or at least this wasn't considered needed before). I think I will change this by adding a new boolean field `readyCheckNeeded` to `PullRequestWorkItem` so we can avoid doing it when not needed, and while at it, I will move `isReady` as well.

**Review by magicus — APPROVED** [review]
LGTM

**Pull request closed without merging**
