### PR TITLE
1188: The pr/NNNN branches are not always deleted when a PR is closed

### PR DESCRIPTION
**Pull request by lgxbslgx**
Hi all,

When a PR is ready for reviewing, the label `rfr` will be added and skara will create the branch `pr/NNNN` for it. 
If we convert the PR back to draft, the label `rfr` would be removed and the branch `pr/NNNN` won't be deleted. 
Then we close the PR, **the bot won't deleted the branch**.

The reason is that the following code checks the label `rfr` or `integrated` to decide whether the bot should remove the branch.

```
    private boolean isOfInterest(PullRequest pr) {
        var labels = new HashSet<>(pr.labelNames());
        if (!(labels.contains("rfr") || labels.contains("integrated"))) {
            log.fine("PR is not yet ready - needs either 'rfr' or 'integrated' label");
            return false;
        }
        // ignore......
    }
```

To solve this issue, this patch adds one situation about the branch existing or not. And the corresponding test is added.

Thanks for taking the time to review.

Best Regards,
-- Guoxiong

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Change must be properly reviewed

### Issue
 * [SKARA-1188](https://bugs.openjdk.java.net/browse/SKARA-1188): The pr/NNNN branches are not always deleted when a PR is closed

### Reviewers
 * [Erik Joelsson](https://openjdk.java.net/census#erikj) (@erikj79 - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/skara pull/1242/head:pull/1242` \
`$ git checkout pull/1242`

Update a local copy of the PR: \
`$ git checkout pull/1242` \
`$ git pull https://git.openjdk.java.net/skara pull/1242/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1242`

View PR using the GUI difftool: \
`$ git pr show -t 1242`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/skara/pull/1242.diff">https://git.openjdk.java.net/skara/pull/1242.diff</a>

</details>

### CODE REVIEW

**Comment by dholmes-ora** [comment]
If the PR is re-opened again will the branch be recreated?

**Comment by lgxbslgx** [comment]
> If the PR is re-opened again will the branch be recreated?

It depends on whether the PR has the label `rfr`. As you can see the condition `labels.contains("rfr") || labels.contains("integrated") || branchExists`, only the PR has label `rfr` or `integrated` or has branch `pr/NNNN`, the `PullRequestWorkItem` would be added to be invoked.

**Comment by lgxbslgx** [comment]
The newly added test case also tests this situation. Please see the following code taken from the test case.

```
            // Reopen the PR
            pr.setState(Issue.State.OPEN);
            TestBotRunner.runPeriodicItems(notifyBot);

            // The target repo should not contain the branch, because the pr doesn't have label `rfr`.
            assertThrows(IOException.class, () -> localRepo.fetch(repo.url(), PreIntegrations.preIntegrateBranch(pr)));

            // add label `rfr`
            pr.addLabel("rfr");
            TestBotRunner.runPeriodicItems(notifyBot);

            // The branch should have reappeared
            hash = localRepo.fetch(repo.url(), PreIntegrations.preIntegrateBranch(pr));
            assertEquals(editHash, hash);
```

**Review by erikj79 — APPROVED** [review]
Looks good and well spotted!

**Comment by lgxbslgx** [comment]
@erikj79 Thanks for your review. Could I get your help to sponsor this patch?

/integrate

**Pull request closed without merging**
