### PR TITLE
SKARA-1194: Implement git webrev --no-comments option

### PR DESCRIPTION
**Pull request by shipilev**
hg webrev had a `-C` / `--no-comments` option that skipped printing the comments for each file, i.e. commit messages. GitWebrev accepts the same option, but it does not seem to be implemented. Producing a webrev for a branch with a lot of commits looks badly then.

For example, current report with `-C`:

```
 ------ ------ ------ ------ --- New Patch Raw doc/panama_jextract.html

    8065b5cc: 8270898: update panama_jextract.md and panama_jextract.html files
    bedc58a3: 8257892: long double not handled by jextract
    2d966367: Consolidate all the various documents in the repository.
    3dc23ea0: 8253419: jextract should generate RuntimeHelper as a package private class
    52adf7f5: updating samples for CSupport->CLinker
    33cba7a0: adding tensorflow sample
    06675b1e: updating samples. changed constants class to use package constructor
    6809ef51: Samples update after 8249879. Added opengl sample
    abb6e377: updating samples for recent MemoryAccess changes.
    ebba5406: 8248710: jextract should not generate Cstring, Cpointer, Cint C-X utility classes
    45d41d75: * Fixed include path to be OS/SDK version independent
    ...

    992 lines changed; 992 ins; 0 del; 0 mod; 0 unchg
```

Fixed report with `-C`:

```
 ------ ------ ------ ------ --- New Patch Raw doc/panama_jextract.html

    992 lines changed; 992 ins; 0 del; 0 mod; 0 unchg 
```

Additional testing:
 - [x] Eyeballing the reports with/without `-C`

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Change must be properly reviewed

### Issue
 * [SKARA-1194](https://bugs.openjdk.java.net/browse/SKARA-1194): Implement git webrev --no-comments option

### Reviewers
 * [Erik Joelsson](https://openjdk.java.net/census#erikj) (@erikj79 - **Reviewer**)
 * [Magnus Ihse Bursie](https://openjdk.java.net/census#ihse) (@magicus - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/skara pull/1224/head:pull/1224` \
`$ git checkout pull/1224`

Update a local copy of the PR: \
`$ git checkout pull/1224` \
`$ git pull https://git.openjdk.java.net/skara pull/1224/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1224`

View PR using the GUI difftool: \
`$ git pr show -t 1224`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/skara/pull/1224.diff">https://git.openjdk.java.net/skara/pull/1224.diff</a>

</details>

### CODE REVIEW

**Comment by shipilev** [comment]
> It's unfortunate to have a field/variable with a negation in the name, but in this case it matches the argument so it could be ok. Maybe worth inverting the internal variable/field? What do you think? I'm approving this as it is if you don't want to.

OK, we can drop "no" from field names and negate it when reading from cli. See new commit.

**Review by erikj79 — APPROVED** [review]
Looks good! Thanks for contributing to Skara!

**Comment by shipilev** [comment]
Thanks!

/integrate

**Review by magicus — APPROVED** [review]

**Pull request closed without merging**
