### PR TITLE
Update jdk.json to include XML Signature tests

### PR DESCRIPTION
**Pull request by wangweij**
There are XML Signature tests inside this directory.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Change must be properly reviewed

### Reviewers
 * [Kevin Rushforth](https://openjdk.java.net/census#kcr) (@kevinrushforth - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/skara pull/1206/head:pull/1206` \
`$ git checkout pull/1206`

Update a local copy of the PR: \
`$ git checkout pull/1206` \
`$ git pull https://git.openjdk.java.net/skara pull/1206/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1206`

View PR using the GUI difftool: \
`$ git pr show -t 1206`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/skara/pull/1206.diff">https://git.openjdk.java.net/skara/pull/1206.diff</a>

</details>

### CODE REVIEW

**Comment by kevinrushforth** [comment]
@wangweij If you are ready to have this reviewed you will need to add a non-empty Description for this PR.

**Comment by wangweij** [comment]
> @wangweij If you are ready to have this reviewed you will need to add a non-empty Description for this PR.

I thought it was not necessary. Just added one. Thanks.

**Review by kevinrushforth — APPROVED** [review]

**Pull request closed without merging**
