### PR TITLE
Add an issue link to RFR mails if the PR title contains one

### PR DESCRIPTION
**Pull request by rwestberg**
Hi all,

Please review this change that adds an issue link to RFR emails if the PR title contains one. It also allows projects to specify their issue key in case it is different from the project name.

Best regards,
Robin

Progress
--------
- [x] Change must not contain extraneous whitespace
- [x] Change must be properly reviewed

Approvers
---------
 * Erik Helin ([ehelin](@edvbld) - **Reviewer**)
 * Kevin Rushforth ([kcr](@kevinrushforth) - no project role)

### CODE REVIEW

**Comment by kevinrushforth** [comment]
This looks great. As a follow-on to this, what about having the bot add the JBS URL as a comment in the PR (maybe as part of the status block along with Progress and Approvers)?

**Comment by edvbld** [comment]
@kevinrushforth it is coming, we are just starting out small :smile:

**Comment by kevinrushforth** [comment]
I'm looking forward to testing this for openjfx, which does have a different JBS prefix than the project name, so I'll be using the `jbs` field in `.jcheck/conf`.

**Pull request closed without merging**
