### PR TITLE
Small updates to jdk.json mapping

### PR DESCRIPTION
**Pull request by jddarcy**
Simplify AIX libjli mapping and remove various HotSpot regression tests from core-libs-dev.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Change must be properly reviewed

### Reviewers
 * Robin Westberg ([rwestberg](@rwestberg) - **Reviewer**) ⚠️ Review applies to a3b54cf4b9714a57a8effb85d194797d2f37d550

### Download
`$ git fetch https://git.openjdk.java.net/skara pull/751/head:pull/751`
`$ git checkout pull/751`

### CODE REVIEW

**Review by rwestberg — APPROVED** [review]
Thanks for the update!

**Comment by jddarcy** [comment]
I condensed down the mappings covering
src/java.base/share/classes/jdk/internal/*
and verified all the previously listed directories where still mapped to core-libs using
git skara debug mlrules -v  $PATH_TO_MODIFIED_FILE

**Pull request closed without merging**
