### PR TITLE
mlrules: applying off-list suggestions

### PR DESCRIPTION
**Pull request by rwestberg**
Hi all,

In this PR I'll collect the various updates to the jdk mailing list rules file that I'm receiving off-list (which is perfectly fine, feel free to send plain suggestions my way and I'll collect them here!)

Best regards,
Robin

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Change must be properly reviewed

### Reviewers
 * Erik Helin ([ehelin](@edvbld) - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/skara pull/746/head:pull/746`
`$ git checkout pull/746`

### CODE REVIEW

**Comment by AlanBateman** [comment]
Thanks, looks good!

**Comment by edvbld** [comment]
I got the feedback from a build-dev maintainer off-list that the following for build-dev:
```
            "bin/idea.sh",
            "bin/jib.sh",
            "bin/unshuffle_list.txt",
            "configure",
            "doc/building.html",
            "doc/building.md",
            "doc/ide.html",
            "doc/ide.md",
            "doc/testing.html",
            "doc/testing.md",
```
can be simplified to just:
```
             "bin/",
             "doc/",
```

**Comment by edvbld** [comment]
Comment from GC maintainer regarding hotspot-gc-dev - change:
```
"src/hotspot/share/memory/(heap|oop)",
```
into
```
"src/hotspot/share/memory/oop",
```

The files `src/hotspot/share/memory/heap.{hpp,cpp}` actually for the code heap (and are thus most often reviewed on hotspot-compiler-dev). As a GC reviewer I should have caught this too :smile:

**Comment by edvbld** [comment]
I received the following feedback regarding `hotspot-compiler-dev` - change:
```
src/jdk.aot/share/classes/jdk.tools.jaotc
```
into just
```
src/jdk.aot/
```
and add the following files:
```
src/hotspot/share/runtime/icache.cpp
src/hotspot/share/runtime/icache.hpp
src/hotspot/share/runtime/registerMap.hpp
src/hotspot/share/runtime/sharedRuntime.cpp
src/hotspot/share/runtime/sharedRuntime.hpp
src/hotspot/share/runtime/sharedRuntimeMath.hpp
src/hotspot/share/runtime/sharedRuntimeTrans.cpp
src/hotspot/share/runtime/sharedRuntimeTrig.cpp
src/hotspot/share/runtime/stubCodeGenerator.hpp
src/hotspot/share/runtime/sweeper.cpp
src/hotspot/share/runtime/sweeper.hpp
src/hotspot/share/runtime/vframe.cpp
src/hotspot/share/runtime/vframe.hpp
src/hotspot/share/runtime/vframe.inline.hpp
src/hotspot/share/runtime/vframeArray.cpp
src/hotspot/share/runtime/vframeArray.hpp
src/hotspot/share/runtime/vframe_hp.cpp
src/hotspot/share/runtime/vframe_hp.hpp
```
As stated in another comment, the following files should also be for `hotspot-compiler-dev`:
```
src/hotspot/share/memory/heap.hpp
src/hotspot/share/memory/heap.inline.hpp
src/hotspot/share/memory/heap.cpp
```

**Comment by edvbld** [comment]
Additional suggestion to add the following for "jdk-dev":
```
README.md
CONTRIBUTING.md
LICENSE
ASSEMBLY_EXCEPTION
ADDITIONAL_LICENSE_INFO
```

**Comment by edvbld** [comment]
Furthermore, please drop the `-dev` suffix from the labels, that can be inferred :+1:

**Comment by edvbld** [comment]
I think the Shenandoah project want `shenandoah-dev` to be CC:d for changes to files in `src/hotspot/share/gc/shenandoah`. See https://mail.openjdk.java.net/pipermail/hotspot-gc-dev/2020-August/030527.html for the source.

**Review by edvbld — APPROVED** [review]
Great improvements!

**Comment by edvbld** [comment]
One more addition: I would probably have coalesced hotspot-gc-dev, hotspot-runtime-dev and hotspot-gc-dev into hotspot-dev.

**Pull request closed without merging**
