### PR TITLE
cli: make it possible to configure forge name

### PR DESCRIPTION
**Pull request by edvbld**
Hi all,

please review this patch that makes it possible to configure the forge name for a repository using `git config forge.name`, for example `git config forge.name github`. This can be useful for speeding up the forge selection logic in `Forge.from` so that the code doesn't have to query multiple candidate forges.

Testing:
- [x] Manual testing on Linux x64

Thanks,
Erik

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Change must be properly reviewed

### Reviewers
 * [Robin Westberg](https://openjdk.java.net/census#rwestberg) (@rwestberg - **Reviewer**)

### Download
To checkout this PR locally:
`$ git fetch https://git.openjdk.java.net/skara pull/1076/head:pull/1076`
`$ git checkout pull/1076`

To update a local copy of the PR:
`$ git checkout pull/1076`
`$ git pull https://git.openjdk.java.net/skara pull/1076/head`

### CODE REVIEW

**Comment by rwestberg** [comment]
Looks good in general, but how about also storing this configuration automatically as well when auto-detection completes successfully (if it's not configured yet)? That way everyone could benefit from it on subsequent runs without having to configure it manually.

**Comment by edvbld** [comment]
> Looks good in general, but how about also storing this configuration automatically as well when auto-detection completes successfully (if it's not configured yet)?

Good idea! See the latest commit for an implementation :smile:

**Review by rwestberg — APPROVED** [review]
Looks good!

**Pull request closed without merging**
