### PR TITLE
1731: Improve RestRequestCache rate limiter

### PR DESCRIPTION
**Pull request by erikj79**
In the RestRequestCache, we are trying to limit non GET calls for a specific host and user to one call per second (and all calls, including GET, for a specific host and user, need to be serialized). This throttling is based on recommendations from GitHub (https://docs.github.com/en/rest/guides/best-practices-for-integrators?apiVersion=2022-11-28#dealing-with-abuse-rate-limits). The current implementation isn't really doing that however. Calls are serialized, but depending on timing, we can definitely send more than one non GET call per second, at least in bursts.

This patch tries to rework this, using two locks. During high contention, it's possible that this new implementation will be less favorable to non GET calls than the current implementation, but I'm pretty sure we will at least adhere to the recommendation of performing at most one non-GET call per second. See bug for breakdown of locking order.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace

### Issue
 * [SKARA-1731](https://bugs.openjdk.org/browse/SKARA-1731): Improve RestRequestCache rate limiter

### Reviewers
 * [Zhao Song](https://openjdk.org/census#zsong) (@zhaosongzs - Committer)
 * [Magnus Ihse Bursie](https://openjdk.org/census#ihse) (@magicus - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/skara pull/1453/head:pull/1453` \
`$ git checkout pull/1453`

Update a local copy of the PR: \
`$ git checkout pull/1453` \
`$ git pull https://git.openjdk.org/skara pull/1453/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1453`

View PR using the GUI difftool: \
`$ git pr show -t 1453`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/skara/pull/1453.diff">https://git.openjdk.org/skara/pull/1453.diff</a>

</details>

### CODE REVIEW

**Review by zhaosongzs — APPROVED** [review]
It really took me a while to understand how it was able to send two non-GET requests in one second, but once I understood it, I checked your revision and I believe that the clever two-lock solution will solve the problem perfectly.

**Comment by magicus** [comment]
Is this not slowing us down unnecessarily? If we have like an incoming stream of requests like this:
GET1 POST1 POST2 GET2 GET3 GET4
Then we will correctly make sure only a single request is sent at a time, and that the two post operations will have a delay between them. But that will also mean that GET2...GET4 will be artificially delayed, awaiting POST1 and POST2.

My understanding is that we should be able to do like:
GET1 POST1 (wait with POST2) GET2 GET3 POST4 (now enough time has passed) GET4

I think this would be easy to accomplish, as well. Just reverse the order on the post locks, so we first take the non-get lock to ensure one second has passed since the last POST operation, and then we take the general lock. That way additional GET requests can be handled while the POST operation is waiting for the full second to pass, but we will still in the end always need to hold the general lock, so we do not send a POST and a GET at the same time.

**Comment by magicus** [comment]
Actually, that is what you are doing. :-)

I got confused by:
```
 var authNonGetLock = authNonGetLocks.computeIfAbsent(authId, id -> new ReentrantLock());
 ```
thinking it was grabbing the lock.

**Review by magicus — APPROVED** [review]

**Pull request closed without merging**
