### PR TITLE
1295: CSRBot throws intermittent exception when looking up JiraIssue links

### PR DESCRIPTION
**Pull request by erikj79**
This patch adds another retry condition for rest requests. When a rest call uses authentication but fails with 401 "unauthorized", we need to give it at least one more try. The authentication mechanism for JBS works with time limited tokens that sometimes need to be renewed. This can only be detected through failing with 401. On the retry, the dynamic authorization provider (authGen.getAuthHeaders()) will get to run again and will detect the stale token.

I'm currently running with this patch live for the affected bot and so far it's looking good, but I will leave it running a while more to make sure.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Change must be properly reviewed

### Issue
 * [SKARA-1295](https://bugs.openjdk.java.net/browse/SKARA-1295): CSRBot throws intermittent exception when looking up JiraIssue links

### Reviewers
 * [Kevin Rushforth](https://openjdk.java.net/census#kcr) (@kevinrushforth - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/skara pull/1268/head:pull/1268` \
`$ git checkout pull/1268`

Update a local copy of the PR: \
`$ git checkout pull/1268` \
`$ git pull https://git.openjdk.java.net/skara pull/1268/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1268`

View PR using the GUI difftool: \
`$ git pr show -t 1268`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/skara/pull/1268.diff">https://git.openjdk.java.net/skara/pull/1268.diff</a>

</details>

### CODE REVIEW

**Comment by erikj79** [comment]
I still see failures. Please ignore this review for now.

**Comment by erikj79** [comment]
I believe I have it working now. Before retrying, the auth headers need to be explicitly overwritten. The currently used headers method just adds more values to the same headers, which the server will most likely not accept.

**Review by kevinrushforth — APPROVED** [review]
Looks good.

**Pull request closed without merging**
