### PR TITLE
1704: Add or update copyright header in some files

### PR DESCRIPTION
**Pull request by zhaosongzs**
The patch just updated copyright headers in some files.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace

### Issue
 * [SKARA-1704](https://bugs.openjdk.org/browse/SKARA-1704): Add or update copyright header in some files

### Reviewers
 * [Magnus Ihse Bursie](https://openjdk.org/census#ihse) (@magicus - **Reviewer**) ⚠️ Review applies to [e69e110d](https://git.openjdk.org/skara/pull/1431/files/e69e110d29d45ce147e552e875f9f836cd790286)
 * [Erik Joelsson](https://openjdk.org/census#erikj) (@erikj79 - **Reviewer**) ⚠️ Review applies to [e69e110d](https://git.openjdk.org/skara/pull/1431/files/e69e110d29d45ce147e552e875f9f836cd790286)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/skara pull/1431/head:pull/1431` \
`$ git checkout pull/1431`

Update a local copy of the PR: \
`$ git checkout pull/1431` \
`$ git pull https://git.openjdk.org/skara pull/1431/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1431`

View PR using the GUI difftool: \
`$ git pr show -t 1431`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/skara/pull/1431.diff">https://git.openjdk.org/skara/pull/1431.diff</a>

</details>

### CODE REVIEW

**Comment by magicus** [comment]
Have you used a script to get the last commit that touched the files to determine the updated copyright year?

**Comment by zhaosongzs** [comment]
> Have you used a script to get the last commit that touched the files to determine the updated copyright year?

No, I just used Intellij to see the git blame, and the last commit will have a '*'.

**Comment by magicus** [comment]
So you updated 350+ files manually? 👀 🙀 

Apart from the fact that this must have been tedious work for you, I recommend in the future that you write a script to do stuff like this, since it is less likely to make a mistake. It is basically impossible for anyone to review if all these files have correct years, and you might have made a mistake when covering this many files. A script, on the other hand, can be presented to the reviewers, and then they can get additional confidence in that it has done the right thing.

**Review by magicus — APPROVED** [review]
... but since you've gone through the effort, I'll rubber-stamp this PR for you.

**Comment by zhaosongzs** [comment]
> So you updated 350+ files manually? 👀 🙀
> 
> Apart from the fact that this must have been tedious work for you, I recommend in the future that you write a script to do stuff like this, since it is less likely to make a mistake. It is basically impossible for anyone to review if all these files have correct years, and you might have made a mistake when covering this many files. A script, on the other hand, can be presented to the reviewers, and then they can get additional confidence in that it has done the right thing.

Ah, yes, I must find a better way to do this. Whatever, it's over for now. 😄

**Comment by magicus** [comment]
For example, here are some one-liners I use to mass-update copyright years:
```
gt diff ${HASH}.. --name-only > ALLNAMES.txt

sed -i  -e 's/Copyright (c) \([0-9]*\), Oracle and\/or its affiliates. All rights reserved./Copyright (c) \1, 2022, Oracle and\/or its affiliates. All rights reserved./g' $(cat ALLNAMES.txt )

sed -i -e 's/Copyright (c) \([0-9]*\), [0-9]*, Oracle and\/or its affiliates. All rights reserved./Copyright (c) \1, 2022, Oracle and\/or its affiliates. All rights reserved./g' $(cat ALLNAMES.txt )
```

**Comment by zhaosongzs** [comment]
> For example, here are some one-liners I use to mass-update copyright years:
> 
> ```
> gt diff ${HASH}.. --name-only > ALLNAMES.txt
> 
> sed -i  -e 's/Copyright (c) \([0-9]*\), Oracle and\/or its affiliates. All rights reserved./Copyright (c) \1, 2022, Oracle and\/or its affiliates. All rights reserved./g' $(cat ALLNAMES.txt )
> 
> sed -i -e 's/Copyright (c) \([0-9]*\), [0-9]*, Oracle and\/or its affiliates. All rights reserved./Copyright (c) \1, 2022, Oracle and\/or its affiliates. All rights reserved./g' $(cat ALLNAMES.txt )
> ```

Oh, thanks! Maybe I could run this script to check whether I made mistakes.

**Comment by magicus** [comment]
Sorry, that was just an example, to built upon. That particular sequence of command will find which files have been changed for a set of git commits, and will update the year to 2022. To get what you need for this PR is a bit more tricky. 

There is a script in the JDK, https://github.com/openjdk/jdk/blob/master/make/scripts/update_copyright_year.sh, which does something along these lines. I don't know if you can just download and run it in Skara, or if it needs adaptation.

**Review by erikj79 — APPROVED** [review]

**Comment by erikj79** [comment]
As I said offline, I assumed you were just going to fix the files you had missed putting a header on recently, but this was a heroic effort, thanks for doing it! As Magnus says, it's probably better to try to automate this kind of change, but even if there is a mistake or two in here, I think we are much closer to being correct with this change than without it. We can always followup with an automated verification later.

**Comment by zhaosongzs** [comment]
> As I said offline, I assumed you were just going to fix the files you had missed putting a header on recently, but this was a heroic effort, thanks for doing it! As Magnus says, it's probably better to try to automate this kind of change, but even if there is a mistake or two in here, I think we are much closer to being correct with this change than without it. We can always followup with an automated verification later.
> 
> I have skimmed through and looked at the formatting.

Thanks, Erik!

**Comment by zhaosongzs** [comment]
> Sorry, that was just an example, to built upon. That particular sequence of command will find which files have been changed for a set of git commits, and will update the year to 2022. To get what you need for this PR is a bit more tricky.
> 
> There is a script in the JDK, https://github.com/openjdk/jdk/blob/master/make/scripts/update_copyright_year.sh, which does something along these lines. I don't know if you can just download and run it in Skara, or if it needs adaptation.

I ran the script in Skara and it worked perfectly! Thank you!

**Pull request closed without merging**
