### PR TITLE
Add pull request prune functionality

### PR DESCRIPTION
**Pull request by rwestberg**
Hi all,

Please review this change that adds another mode to the bridgekeeper bot that closes PRs after a configurable period of inactivity.

Best regards,
Robin

## Progress
- [x] Change must not contain extraneous whitespace
- [x] Change must be properly reviewed

## Approvers
 * Erik Helin ([ehelin](@edvbld) - **Reviewer**) **Note!** Review applies to 83c41425a240e4e8d6e7f24a4135b8abe7caec1c
 * Kevin Rushforth ([kcr](@kevinrushforth) - no project role)

### CODE REVIEW

**Comment by kevinrushforth** [comment]
What is the motivation for doing this? I'm not sure that I would find this a useful behavior.

**Comment by rwestberg** [comment]
This will allow stale pull requests to eventually be closed, without manual intervention. The duration can be configured per project (or not enabled at all), as different projects may have different needs.

**Comment by rwestberg** [comment]
After discussing this a bit with Kevin offline, I've updated the logic a bit to send an initial notice before proceeding with the actual close.

**Comment by rwestberg** [comment]
@edvbld Please have another look!

**Comment by rwestberg** [comment]
@kevinrushforth  Thanks for reviewing!

**Pull request closed without merging**
