### PR TITLE
Build: Update to JDK 15.0.2

### PR DESCRIPTION
**Pull request by oscerd**
Hello all,

Just a little PR for upgrading to JDK 15.0.2.

make images passed fine and make test too.

Thank you

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Change must be properly reviewed

### Reviewers
 * [Erik Helin](https://openjdk.java.net/census#ehelin) (@edvbld - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/skara pull/989/head:pull/989`
`$ git checkout pull/989`

### CODE REVIEW

**Comment by oscerd** [comment]
I believe I'm covered under the blanket Red Hat agreement

**Comment by oscerd** [comment]
Am I supposed to do something now?

**Comment by gunnarmorling** [comment]
Hey @robilad, could you kick off the OCA verification for fellow Red Hatter @oscerd?

**Comment by oscerd** [comment]
Thanks @gunnarmorling :-)

**Comment by robilad** [comment]
Thanks, I have marked the account as verified.

**Comment by edvbld** [comment]
Thanks for contributing @oscerd! Would you mind enabling GitHub Actions in your [fork](https://github.com/oscerd/skara/actions) so that the CI tests can be run?

Thanks!
Erik

**Comment by oscerd** [comment]
Done

**Comment by oscerd** [comment]
I don't know if there is something else to do on my side.

**Comment by edvbld** [comment]
@oscerd you can just merge the `master` into your branch `jdk-15.0.2` (the merge commit will be automatically squashed when we integrate your changes, so don't worry). Then push the merge commit, then the GitHub Actions will be triggered :+1:

**Comment by oscerd** [comment]
Done

**Comment by oscerd** [comment]
Thanks for helpin on the workflow. All seems to be ok.

**Review by edvbld — APPROVED** [review]
Looks good! :tada:

**Comment by oscerd** [comment]
Thanks for reviewing, we now need a second reviewer right?

**Comment by edvbld** [comment]
> Thanks for reviewing, we now need a second reviewer right?

No, Skara only requires one Reviewer (otherwise the bot wouldn't have labelled this as "ready'). You are good to go, just follow the bot's instructions :robot:

**Pull request closed without merging**
