### PR TITLE
2039: Only post ApprovalNeededComment when the user hasn't applied for maintainer approval for all the issues

### PR DESCRIPTION
**Pull request by zhaosongzs**
In [SKARA-1949](https://bugs.openjdk.org/browse/SKARA-1949), we introduced /approval command and at the same time, we let the bot post ApprovalNeededComment when the pull request is reviewed.

As Kevin Rushforth suggested, the bot shouldn't post ApprovalNeededComment if the user already applied for all the issues.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace

### Issue
 * [SKARA-2039](https://bugs.openjdk.org/browse/SKARA-2039): Only post ApprovalNeededComment when the user hasn't applied for maintainer approval for all the issues (**Bug** - P4)

### Reviewers
 * [Erik Joelsson](https://openjdk.org/census#erikj) (@erikj79 - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/skara.git pull/1606/head:pull/1606` \
`$ git checkout pull/1606`

Update a local copy of the PR: \
`$ git checkout pull/1606` \
`$ git pull https://git.openjdk.org/skara.git pull/1606/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1606`

View PR using the GUI difftool: \
`$ git pr show -t 1606`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/skara/pull/1606.diff">https://git.openjdk.org/skara/pull/1606.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/skara/pull/1606#issuecomment-1912757257)

### CODE REVIEW

**Comment by kevinrushforth** [comment]
> the bot shouldn't post ApprovalNeededComment if the user already applied for at least one of the issues.

For multiple issues, should the `ApprovalNeededComment` be posted if one (or more) of the issues is missing the approval request? In that case you would only skip posting the message if _all_ of the issues have the approval request.

**Comment by zhaosongzs** [comment]
> > the bot shouldn't post ApprovalNeededComment if the user already applied for at least one of the issues.
> 
> For multiple issues, should the `ApprovalNeededComment` be posted if one (or more) of the issues is missing the approval request? In that case you would only skip posting the message if _all_ of the issues have the approval request.

I was thinking post` ApprovalNeededComment` only when all the issues have the request, but later, I think that if there is one issue contains the request, then it means the user knows how to make the request. So no need to post the comment.

**Comment by erikj79** [comment]
> > > the bot shouldn't post ApprovalNeededComment if the user already applied for at least one of the issues.
> > 
> > 
> > For multiple issues, should the `ApprovalNeededComment` be posted if one (or more) of the issues is missing the approval request? In that case you would only skip posting the message if _all_ of the issues have the approval request.
> 
> I was thinking post` ApprovalNeededComment` only when all the issues have the request, but later, I think that if there is one issue contains the request, then it means the user knows how to make the request. So no need to post the comment.

I think I agree with Kevin. If any issue is missing the approval request, post the reminder. The user may have missed one unintentionally.

**Comment by zhaosongzs** [comment]
> > > > the bot shouldn't post ApprovalNeededComment if the user already applied for at least one of the issues.
> > > 
> > > 
> > > For multiple issues, should the `ApprovalNeededComment` be posted if one (or more) of the issues is missing the approval request? In that case you would only skip posting the message if _all_ of the issues have the approval request.
> > 
> > 
> > I was thinking post` ApprovalNeededComment` only when all the issues have the request, but later, I think that if there is one issue contains the request, then it means the user knows how to make the request. So no need to post the comment.
> 
> I think I agree with Kevin. If any issue is missing the approval request, post the reminder. The user may have missed one unintentionally.

OK,  I will fix it.

**Review by erikj79 — APPROVED** [review]

**Comment by zhaosongzs** [comment]
Thanks for the review!
/integrate

**Pull request closed without merging**
